# deployment files are ERB files
<% require "dotenv"; Dotenv.load(".env") %>

# Name of your application
# Used to uniquely configure containers.
service: vote-ui

# Name of the container image under which it will be pushed/pulled to/from registry
image: bcachet/votingapp/vote-ui

# Define role to be 
primary_role: web
servers:
  web:
    hosts: <%= ENV.fetch('WEB_SERVERS').split(' ') %>
    env:
      clear:
        VOTE_URL: http://127.0.0.1:5000/
    # Configure kamal-proxy to route traffic to our service/container
    proxy:
      ssl: false
      ## When no hosts are set, all requests are forwarded to container
      # host: nil
      ## Proxy connects to your container on port 80 by default.
      app_port: 80
      healthcheck:
        interval: 1
        path: /
        timeout: 5
    logging:
      driver: json-file
      options:
        max-size: 100m

# Configure builder setup.
builder:
  arch: amd64
  dockerfile: ./vote-ui/Dockerfile
  context: ./vote-ui/

# SSH configuration comes from external file to be shared amongst deployment
<%
template = File.read('./config/ssh.yml')
ssh = ERB.new(template)
%>
<%= ssh.result %>

# Registry configuration come from external file to be shared accross all deployments
<%= File.read('./config/registry.yml') %>
