# Name of your application. Used to uniquely configure containers.
service: vote

# Name of the container image.
image: bcachet/votingapp/vote

allow_empty_roles: false
retain_containers: 2
primary_role: web
servers:
  web:
    hosts: 
      - 85.217.161.102
    env:
      clear:
        REDIS_URL: redis://85.217.161.72:6379
        BACKEND: db
    proxy:
      ssl: false
      ## When no hosts are set, all requests are forwarded to container
      # host: 
      ## Proxy connects to your container on port 80 by default.
      app_port: 5000
      healthcheck:
        interval: 1
        path: /healthz
        timeout: 5
    logging:
      driver: json-file
      options:
        max-size: 100m

# Container registry configuration
registry:
  server: ghcr.io
  username: bcachet
  password:
    - GHCR_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64
  dockerfile: ./vote/Dockerfile
  context: ./vote

ssh:
  # key_data: <%= [ ENV["TF_VAR_private_key"] ] %>
  keys:
    - ./config/private_key.pem
  user: ubuntu
  port: 22
  keys_only: true
  config: false

# Use accessory services (secrets come from .kamal/secrets).
#
accessories:
  redis:
    service: redis
    image: valkey/valkey:8
    hosts:
      - 85.217.161.72
    port: 6379
    directories:
      - data:/data
    options:
      restart: always
    proxy: false
